repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-merge-conflict

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: end-of-file-fixer

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.1
  hooks:
    # Run the linter and fix the issues.
    - id: ruff-check
      args: [--fix, --exit-non-zero-on-fix]
    # Run the formatter.
    - id: ruff-format
